# Generated by Django 2.0.3 on 2018-05-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingprofile_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
