# Generated by Django 2.0.3 on 2018-04-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_total',
        ),
    ]
