# Generated by Django 2.0.3 on 2018-04-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180425_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(default='abc'),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
