# Generated by Django 2.0.3 on 2018-04-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180425_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
