# Generated by Django 2.0.3 on 2018-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180427_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=10),
        ),
    ]
